### ISSUE TITLE
Error: listen EACCES 0.0.0.0:80

### ISSUE THREAD

**Issue by bbrinx** [kireerik/razzle-material-ui-styled-example#2]
After installing the dependencies successfully, running `yarn start` results in an error. It compiled the client and server successfully, but then suddenly fails at events.js:182

```
Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:1016:11)
    at exports._exceptionWithHostPort (util.js:1039:20)
    at Server.setupListenHandle [as _listen2] (net.js:1290:19)
    at listenInCluster (net.js:1355:12)
    at Server.listen (net.js:1455:7)
    at Function.listen (/mypath/razzle-material-ui-styled-example-master/node_modules/express/lib/application.js:618:24)
    at Object../src/index.js (/mypath/razzle-material-ui-styled-example-master/build/server.js:219:4)
    at __webpack_require__ (/mypath/razzle-material-ui-styled-example-master/build/server.js:20:30)
    at Object.15 (/mypath/razzle-material-ui-styled-example-master/build/server.js:329:18)
    at __webpack_require__ (/mypath/razzle-material-ui-styled-example-master/build/server.js:20:30)

error Command failed with exit code 1.
```

**Comment by kireerik** [comment]
Hi @bbrinx, may I ask you what kind of environment are you using? It is possible that something else is already running on port `80` on your system or you may need root permission to run the application on port `80`. You can change the port [here](https://github.com/kireerik/razzle-material-ui-styled-example/blob/master/.env#L2) (you may remove that line, because the default port is `3000`).
