### ISSUE TITLE
yarn start bug 

### ISSUE THREAD

**Issue by nolawi** [kireerik/razzle-material-ui-styled-example#3]
`yarn start v0.24.6
$ razzle build && cross-env NODE_ENV=production node build/server.js
Creating an optimized production build...
Compiling client...
Compiled client successfully.
Compiling server...
Compiled server successfully.
Compiled successfully.

File sizes after gzip:

  163.02 KB  build/static/js/client.4773ebe0.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1249:19)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at EventEmitter.listen (/Users/nolawipetros/git/razzle-material-ui-styled-example/node_modules/express/lib/application.js:618:24)
    at Object../src/index.js (/Users/nolawipetros/git/razzle-material-ui-styled-example/build/server.js:219:4)
    at __webpack_require__ (/Users/nolawipetros/git/razzle-material-ui-styled-example/build/server.js:20:30)
    at Object.15 (/Users/nolawipetros/git/razzle-material-ui-styled-example/build/server.js:329:18)
    at __webpack_require__ (/Users/nolawipetros/git/razzle-material-ui-styled-example/build/server.js:20:30)
error Command failed with exit code 1.`

**Comment by kireerik** [comment]
https://github.com/kireerik/razzle-material-ui-styled-example/issues/2#issuecomment-314077767
